baseURL = 'https://joshisp04.github.io/'
languageCode = 'en-us'
title = 'My Portfolio'
theme = 'coder'

[params]
  author = "Shrikrishna Joshi"
  info = "Backend Developer"
  description = "Shrikrishna Joshi's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github"
  weight = 1
  url = "https://github.com/joshisp04/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/shrikrishna-joshi/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"